### PR TITLE
Add private pastie

### PR DESCRIPTION
**Pull request by simmel**
A bit late, but here it is.

Closes #2

### CODE REVIEW

**Comment by tpope** [comment]
I don't use this plugin anymore so I am merging blind. Do you (or anyone else) want ownership?

**Comment by simmel** [comment]
@tpope I will take ownership of it, thank you.

**Comment by tpope** [comment]
I ask that you leave the `Author:` header and add your own `Maintainer:` header. Best of luck.

**Comment by simmel** [comment]
Thank you @tpope! Done in 755b829

**Pull request merged**
